Repository redBorder/cookbook-webui, pull requests merged in 2024-06, with the labels that each got.

#27 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/providers/config.rb
  resources/recipes/configure_db.rb
  resources/recipes/configure_modules.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, refactor, lint, size/XL

#28 Release 0.1.10
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/configure_db.rb
  resources/recipes/configure_modules.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation

#29 Configure nginx load balancer with all nodes
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/webui.conf.erb
Labels: kind/feature, size/XS

#30 Release 0.1.11
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/webui.conf.erb
Labels: kind/documentation, size/S

#31 Add memcached servers to webui
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/memcached_config.yml.erb
Labels: kind/feature, size/XS

#32 Release 0.1.13
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/memcached_config.yml.erb
Labels: kind/documentation, size/S
