Repository redBorder/cookbook-webui, pull requests merged in 2024-07, with the labels that each got.

#36 Bugfix/#18058 fix call migrate dittoc assets on updates
  resources/providers/config.rb
Labels: kind/bug, size/M

#37 Release 0.1.14
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
Labels: kind/documentation, size/M

#35 Feature/#17728 Integration with SAML
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/redborder_config.yml.erb
Labels: kind/feature, size/S

#40 Release 0.2.0
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/redborder_config.yml.erb
Labels: kind/documentation, size/S

#38 Create random 128 bit serial for ssl cert serial
  resources/libraries/helper.rb
Labels: size/XS, kind/bug

#42 Release 0.2.3
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
Labels: size/S
